/var/spool/pbs/mom_priv/jobs/26843.login.hpc.SC: line 7: cd: neural_ca/pytorch_ca: No such file or directory
wandb: Starting wandb agent üïµÔ∏è
wandb: Starting wandb agent üïµÔ∏è
2021-09-30 16:19:38,888 - wandb.wandb_agent - INFO - Running runs: []
2021-09-30 16:19:38,928 - wandb.wandb_agent - INFO - Running runs: []
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
Retry attempt failed:
Traceback (most recent call last):
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 136, in execute
    six.reraise(*sys.exc_info())
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
Retry attempt failed:
Traceback (most recent call last):
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 136, in execute
    six.reraise(*sys.exc_info())
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/u/dssc/s277227/.conda/envs/gpu/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
wandb: Network error (HTTPError), entering retry loop.
wandb: Network error (HTTPError), entering retry loop.
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
500 response executing GraphQL.
{"errors":[{"message":"invalid character 'N' looking for beginning of value","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: invalid character 'N' looking for beginning of value (<Response [500]>)
